# development environment for holopy
#
# To use:
#   conda env create -f ./environment.yml
# and then
#   conda activate holopy-devel
#
# To update dependencies after changing this environment file:
#   conda env update --name holopy-devel --file environment.yml --prune
#
# can also use mamba instead of conda in the above
name: holopy-devel
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy<1.21
  - scipy
  - pyyaml
  # pillow 10.4.0 and later require numpy versions higher than 1.20.3. Tests
  # will not work with these later versions of pillow.
  - pillow<10.4.0
  - pandas=1.5.3
  - xarray
  - h5netcdf
  - h5py
  - numexpr
  - emcee=2.2.1
  # schwimmbad 0.4 and later use multiprocess and dill rather than
  # multiprocessing and pickle. This change may require us to change
  # serialization of HoloPy objects
  - schwimmbad<0.4.0
  - cma

  # for building documentation
  - sphinx
  - sphinx_rtd_theme
  - numpydoc
  - matplotlib

  # for building fortran extensions and python package
  - meson
  - meson-python
  - gfortran

  # linting
  - ruff

  # for running tests: "cov" is coverage plugin, "xdist" is to run pytest in
  # parallel; "timeout" is to set timeout for tests. memory_profiler is needed
  # for one test in test_io.py
  - pytest
  - pytest-cov
  - pytest-xdist
  - pytest-timeout
  - memory_profiler

  # optional packages to make development easier in (e.g.) emacs
  - pyright
  - pylint
  - flake8
  - flake8-pytest-style
  - autoflake
  - epc
  - isort
  - yapf
  - debugpy
  - pip

  - pip:
      - importmagic

  # for interactive use
  - ipython
  - seaborn
  - jupyterlab

