name: build and test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    # conda enviroment activation requires bash
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9"] # , "3.10", "3.11", "3.12"]
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: truncate environment file to include only necessary packages
      shell: bash -el {0}
      run: |
        awk -F '# optional' '{print $1} NF>1{exit}' environment.yml > environment-truncated.yml
    - name: Set up miniforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: environment-truncated.yml
        miniforge-version: latest
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Check versions of gfortran and gcc
      shell: bash -el {0}
      run: |
        conda info
        conda list
        # gfortran in path should be the one installed by conda
        # compare the version below to that reported by 'conda list' above
        which gfortran
        gfortran --version
        which gcc
        gcc --version
    - name: Build package and install
      run: |
        python -m pip install --no-build-isolation --editable .
    - name: Test with pytest and run doctests
      run: |
        python run_tests.py
